#!/usr/bin/env python
from __future__ import print_function
import sys
import os

pipe = '/run/ibossreg'

if len(sys.argv) != 2:
    print('Usage: ibossregctl <group number>')
    sys.exit(1)

group = sys.argv[1]
try:
    fno = os.open(pipe, os.O_RDWR)
    f = os.fdopen(fno, 'w')
    f.write(group)
    f.write('\n')
    print('Group updated to {0}.'.format(group))
except PermissionError:
    print('Permission denied. Make sure you have permission to write to {0}.'.format(pipe))
    sys.exit(1)
except:
    print('Unable to communicate with ibossreg daemon. Is it running?')
    sys.exit(1)
finally:
    try:
        f.close()
    except:
        pass
